const developer = (prefix) => { 
	return `
╭──────「 *ABOUT CREATOR* 」
┴
ASSALAMUALAIKUM TEMAN TEMAN, BUAT KALIAN SEMUA YANG DARI SUBSCRIBERS ARIFI RAZZAQ OFFICIAL, TERIMAKASIH BANYAK UDAH SUPPORT SAMPAI SEJAUH INI. 

SINGKAT PENJELASAN AJA, BUAT KALIAN YANG INGIN AMBIL CASE TOLONG IZIN, DAN BUAT KALIAN REMAKE HINGGA SEMUANYA DI UBAH, TOLONG JANGAN SEPERTI ITU, JANGAN HILANGKAN SAYA DALAM DATABASE SCRIPT BOT WHATSAPP, DAN JANGAN HILANGKAN JUGA CREDIT CREATOR-CREATOR SANAD KARANGAN SCRIPT WHATSAPP BOT SEBELUMNYA.MUNGKIN  ITU AJA YANG AKU SAMPAIKAN, DI BAWAH INI ADA BEBERAPA INFO TENTANG AKU

● *SOSIAL MEDIA :*

INI INSTAGRAM AKU
https://www.instagram.com/arifirazzaq2001
AKUN KE DUA AKU
https://www.instagram.com/arifirazzaqofficial
INI OFFICIAL AKUN YOUTUBE AKU
https://bit.ly/2Lt9XYG
CHANNEL YOUTUBE GAMING AKU
https://bit.ly/3pTF9PP




*DONASI :*

 اتَّقوا النَّارَ ولو بشقِّ تمرةٍ ، فمن لم يجِدْ فبكلمةٍ طيِّبةٍ
_“jauhilah api neraka, walau hanya dengan bersedekah sebiji kurma (sedikit). Jika kamu tidak punya, maka bisa dengan kalimah thayyibah” [HR. Bukhari 6539, Muslim 1016]_

VIA LINK SAWERIA
https://bit.ly/2N2SCpD
VIA DANA
0822-7410-2032
VIA OVO
0822-7410-2032
VIA GOPAY
0822-7410-2032

*BEBAS KALIAN MAU DONASI BERAPA, SEMOGA KALIAN SEMUA DI MUDAHKAN REZEKINYA AAMIIN*`
}
exports.developer = developer